<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "site_config"
 *
 * Auto generated by Extension Builder 2015-06-15
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Site configuration',
	'description' => 'Site configuration',
	'category' => 'plugin',
	'author' => '王者',
	'author_email' => 'it.support@qq.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0',
	'constraints' => array(
		'depends' => array(
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);