<?php
return [
    'ALIPAY' => [
        'account' => '',
        'key' => '',
        'partner' => '',
        'service' => 'create_direct_pay_by_user',
    ],
    'BE' => [
        'debug' => false,
        'explicitADmode' => 'explicitAllow',
        'installToolPassword' => '$P$C7QcsFebu8m6nqVpbdPzSNYDaABCuQ/',
        'loginSecurityLevel' => 'rsa',
        'versionNumberInFilename' => '0',
    ],
    'CERTIFICATE' => [
        'date' => '750,645',
        'header' => '150,250',
        'money' => '320,346',
        'number' => '30,645',
        'prefix' => 'NGO',
    ],
    'DB' => [
        'database' => 'jidian_jy',
        'extTablesDefinitionScript' => 'extTables.php',
        'host' => '127.0.0.1',
        'password' => 'dk265P&',
        'port' => 3306,
        'socket' => '',
        'username' => 'jidian',
    ],
    'EXT' => [
        'extConf' => [
            'backend' => 'a:3:{s:9:"loginLogo";s:58:"fileadmin/templates/backend/public/images/logo-backend.png";s:19:"loginHighlightColor";s:7:"#00CC65";s:20:"loginBackgroundImage";s:59:"fileadmin/templates/backend/public/images/typo3-backend.jpg";}',
            'datamints_feuser' => 'a:3:{s:10:"enableIrre";s:1:"0";s:13:"encryptionKey";s:32:"b98OQ8c5hhmH1dwVyk3po8K8I9kQ0KHm";s:16:"enableSalesforce";s:1:"0";}',
            'dce' => 'a:4:{s:16:"filebasedDcePath";s:24:"fileadmin/templates/dce/";s:21:"disableAutoClearCache";s:1:"0";s:17:"disableCodemirror";s:1:"0";s:17:"enableUpdateCheck";s:1:"0";}',
            'donate' => 'a:10:{s:14:"alipay_account";s:0:"";s:14:"alipay_partner";s:0:"";s:10:"alipay_key";s:0:"";s:8:"wx_appid";s:0:"";s:8:"wx_mchid";s:0:"";s:6:"wx_key";s:0:"";s:12:"wx_appsecret";s:0:"";s:11:"header_name";s:7:"110,555";s:5:"money";s:7:"220,618";s:6:"number";s:6:"40,835";}',
            'fed' => 'a:0:{}',
            'feedit' => 'a:0:{}',
            'flux' => 'a:4:{s:9:"debugMode";s:1:"0";s:15:"disableCompiler";s:1:"0";s:7:"compact";s:1:"0";s:12:"handleErrors";s:1:"0";}',
            'html5videoplayer' => 'a:3:{s:20:"generalStorageFolder";s:1:"0";s:14:"generalMinWith";s:3:"200";s:16:"generalMinHeight";s:3:"150";}',
            'indexed_search' => 'a:18:{s:8:"pdftools";s:9:"/usr/bin/";s:8:"pdf_mode";s:2:"20";s:5:"unzip";s:9:"/usr/bin/";s:6:"catdoc";s:9:"/usr/bin/";s:6:"xlhtml";s:9:"/usr/bin/";s:7:"ppthtml";s:9:"/usr/bin/";s:5:"unrtf";s:9:"/usr/bin/";s:9:"debugMode";s:1:"0";s:18:"fullTextDataLength";s:1:"0";s:23:"disableFrontendIndexing";s:1:"0";s:21:"enableMetaphoneSearch";s:1:"1";s:6:"minAge";s:2:"24";s:6:"maxAge";s:1:"0";s:16:"maxExternalFiles";s:1:"5";s:26:"useCrawlerForExternalFiles";s:1:"0";s:11:"flagBitMask";s:3:"192";s:16:"ignoreExtensions";s:0:"";s:17:"indexExternalURLs";s:1:"0";}',
            'itypo_404handler' => 'a:0:{}',
            'lfeditor' => 'a:4:{s:13:"viewLanguages";s:2:"ch";s:15:"defaultLanguage";s:0:"";s:9:"extIgnore";s:23:"/^(CVS|.svn|.git|csh_)/";s:13:"changeXlfDate";s:1:"1";}',
            'mediace' => 'a:0:{}',
            'news' => 'a:17:{s:29:"removeListActionFromFlexforms";s:1:"1";s:20:"pageModuleFieldsNews";s:317:"LLL:EXT:news/Resources/Private/Language/locallang_be.xlf:pagemodule_simple=title,datetime;LLL:EXT:news/Resources/Private/Language/locallang_be.xlf:pagemodule_advanced=title,datetime,teaser,categories;LLL:EXT:news/Resources/Private/Language/locallang_be.xlf:pagemodule_complex=title,datetime,teaser,categories,archive;";s:24:"pageModuleFieldsCategory";s:17:"title,description";s:11:"archiveDate";s:4:"date";s:13:"prependAtCopy";s:1:"1";s:6:"tagPid";s:1:"1";s:25:"showMediaDescriptionField";s:1:"0";s:12:"rteForTeaser";s:1:"0";s:22:"contentElementRelation";s:1:"0";s:13:"manualSorting";s:1:"0";s:19:"categoryRestriction";s:4:"none";s:34:"categoryBeGroupTceFormsRestriction";s:1:"0";s:6:"useFal";s:1:"1";s:12:"showImporter";s:1:"0";s:18:"storageUidImporter";s:1:"1";s:22:"resourceFolderImporter";s:12:"/news_import";s:24:"showAdministrationModule";s:1:"0";}',
            'news_front_edit' => 'a:0:{}',
            'payment' => 'a:10:{s:14:"alipay_account";s:0:"";s:14:"alipay_partner";s:0:"";s:10:"alipay_key";s:0:"";s:8:"wx_appid";s:0:"";s:8:"wx_mchid";s:0:"";s:6:"wx_key";s:0:"";s:12:"wx_appsecret";s:0:"";s:11:"header_name";s:0:"";s:5:"money";s:0:"";s:6:"number";s:0:"";}',
            'phpexcel_service' => 'a:0:{}',
            'powermail' => 'a:8:{s:12:"disableIpLog";s:1:"0";s:27:"disableMarketingInformation";s:1:"0";s:20:"disableBackendModule";s:1:"0";s:24:"disablePluginInformation";s:1:"0";s:13:"enableCaching";s:1:"0";s:28:"enableTableGarbageCollection";s:1:"0";s:15:"l10n_mode_merge";s:1:"0";s:29:"replaceIrreWithElementBrowser";s:1:"0";}',
            'realurl' => 'a:5:{s:10:"configFile";s:69:"fileadmin/templates/backend/private/configuration/realurl/default.php";s:14:"enableAutoConf";s:1:"0";s:14:"autoConfFormat";s:1:"0";s:12:"enableDevLog";s:1:"0";s:19:"enableChashUrlDebug";s:1:"0";}',
            'recycler' => 'a:0:{}',
            'restdoc' => 'a:2:{s:19:"cache_plugin_output";s:1:"0";s:25:"enable_slash_as_separator";s:1:"0";}',
            'rn_base' => 'a:11:{s:13:"verboseMayday";s:1:"0";s:11:"dieOnMayday";s:1:"1";s:21:"forceException4Mayday";s:1:"1";s:16:"exceptionHandler";s:0:"";s:20:"sendEmailOnException";s:0:"";s:9:"fromEmail";s:0:"";s:24:"send503HeaderOnException";s:1:"1";s:17:"loadHiddenObjects";s:1:"0";s:13:"activateCache";s:1:"0";s:18:"activateSubstCache";s:1:"0";s:8:"debugKey";s:0:"";}',
            'rsaauth' => 'a:1:{s:18:"temporaryDirectory";s:0:"";}',
            'rtehtmlarea' => 'a:8:{s:21:"noSpellCheckLanguages";s:23:"ja,km,ko,lo,th,zh,b5,gb";s:15:"AspellDirectory";s:15:"/usr/bin/aspell";s:20:"defaultConfiguration";s:105:"Typical (Most commonly used features are enabled. Select this option if you are unsure which one to use.)";s:12:"enableImages";s:1:"1";s:20:"enableInlineElements";s:1:"0";s:19:"allowStyleAttribute";s:1:"1";s:24:"enableAccessibilityIcons";s:1:"0";s:16:"forceCommandMode";s:1:"0";}',
            'saltedpasswords' => 'a:2:{s:3:"BE.";a:4:{s:21:"saltedPWHashingMethod";s:41:"TYPO3\\CMS\\Saltedpasswords\\Salt\\PhpassSalt";s:11:"forceSalted";i:0;s:15:"onlyAuthService";i:0;s:12:"updatePasswd";i:1;}s:3:"FE.";a:5:{s:7:"enabled";i:1;s:21:"saltedPWHashingMethod";s:41:"TYPO3\\CMS\\Saltedpasswords\\Salt\\PhpassSalt";s:11:"forceSalted";i:0;s:15:"onlyAuthService";i:0;s:12:"updatePasswd";i:1;}}',
            'site_config' => 'a:0:{}',
            't3users' => 'a:6:{s:18:"enableLoginByEmail";s:1:"0";s:9:"extendTCA";s:1:"1";s:18:"useBeforelastLogin";s:1:"1";s:10:"trackLogin";s:1:"0";s:22:"fullModuleForNonAdmins";s:1:"0";s:16:"activateBeModule";s:1:"0";}',
            'upload_example' => 'a:0:{}',
        ],
    ],
    'EXTCONF' => [
        'lang' => [
            'availableLanguages' => [
                'ch',
            ],
        ],
    ],
    'FE' => [
        'baseURL' => '',
        'beian' => '京ICP备XXXXXX号',
        'debug' => false,
        'lifetime' => '86400',
        'loginSecurityLevel' => 'rsa',
        'pageNotFoundOnCHashError' => '0',
        'pageNotFound_handling' => 'REDIRECT:404/',
        'pageUnavailable_handling' => '',
        'permalogin' => '0',
    ],
    'GFX' => [
        'colorspace' => 'sRGB',
        'im' => 1,
        'im_mask_temp_ext_gif' => 1,
        'im_path' => '/usr/bin/',
        'im_path_lzw' => '/usr/bin/',
        'im_v5effects' => 1,
        'im_version_5' => 'im6',
        'image_processing' => 1,
        'jpg_quality' => '80',
    ],
    'INSTALL' => [
        'wizardDone' => [
            'GeorgRinger\News\Updates\FalUpdateWizard' => 1,
            'GeorgRinger\News\Updates\TtContentRelation' => 1,
            'TYPO3\CMS\Install\Updates\AccessRightParametersUpdate' => 1,
            'TYPO3\CMS\Install\Updates\BackendUserStartModuleUpdate' => 1,
            'TYPO3\CMS\Install\Updates\Compatibility6ExtractionUpdate' => 1,
            'TYPO3\CMS\Install\Updates\ContentTypesToTextMediaUpdate' => 1,
            'TYPO3\CMS\Install\Updates\FileListIsStartModuleUpdate' => 1,
            'TYPO3\CMS\Install\Updates\FilesReplacePermissionUpdate' => 1,
            'TYPO3\CMS\Install\Updates\LanguageIsoCodeUpdate' => 1,
            'TYPO3\CMS\Install\Updates\MediaceExtractionUpdate' => 1,
            'TYPO3\CMS\Install\Updates\MigrateMediaToAssetsForTextMediaCe' => 1,
            'TYPO3\CMS\Install\Updates\MigrateShortcutUrlsAgainUpdate' => 1,
            'TYPO3\CMS\Install\Updates\OpenidExtractionUpdate' => 1,
            'TYPO3\CMS\Install\Updates\PageShortcutParentUpdate' => 1,
            'TYPO3\CMS\Install\Updates\ProcessedFileChecksumUpdate' => 1,
            'TYPO3\CMS\Install\Updates\TableFlexFormToTtContentFieldsUpdate' => 1,
            'TYPO3\CMS\Install\Updates\WorkspacesNotificationSettingsUpdate' => 1,
            'TYPO3\CMS\Rtehtmlarea\Hook\Install\DeprecatedRteProperties' => 1,
            'TYPO3\CMS\Rtehtmlarea\Hook\Install\RteAcronymButtonRenamedToAbbreviation' => 1,
        ],
    ],
    'MAIL' => [
        'defaultMailFromAddress' => 'info@ngoos.org',
        'defaultMailFromName' => '极益NGO系统',
        'transport' => 'mail',
        'transport_sendmail_command' => '/usr/sbin/sendmail -t -i ',
        'transport_smtp_encrypt' => '',
        'transport_smtp_password' => '',
        'transport_smtp_server' => 'localhost:25',
        'transport_smtp_username' => '',
    ],
    'SEO' => [
        'author' => '极益科技',
        'baidukey' => '86182364d0158f1f178baf544d8585f2',
        'description' => '愿景：极致公益 使命：以开源技术推动公益发展 任务：打造极其易用的公益操作系统',
        'keywords' => '极益NGOOS, NGO, 极益科技',
    ],
    'STYLE' => [
        'aHoverColor' => '',
        'bannerBgColor' => '',
        'navBgColor' => '',
    ],
    'SYS' => [
        'UTF8filesystem' => '1',
        'caching' => [
            'cacheConfigurations' => [
                'extbase_object' => [
                    'backend' => 'TYPO3\\CMS\\Core\\Cache\\Backend\\Typo3DatabaseBackend',
                    'frontend' => 'TYPO3\\CMS\\Core\\Cache\\Frontend\\VariableFrontend',
                    'groups' => [
                        'system',
                    ],
                    'options' => [
                        'defaultLifetime' => 0,
                    ],
                ],
            ],
        ],
        'clearCacheSystem' => false,
        'devIPmask' => '',
        'displayErrors' => 0,
        'enableDeprecationLog' => false,
        'encryptionKey' => '0e953fe9e7652aedcb63e287d4bd15de7a5e3330dcfb190ef83dd73c9cf409d12c16f342f5b407d7811c21e78ac84acd',
        'isInitialDatabaseImportDone' => true,
        'isInitialInstallationInProgress' => false,
        'sitename' => '奇点公益',
        'sqlDebug' => 0,
        'systemLocale' => 'en_US.UTF-8',
        'systemLogLevel' => 2,
        't3lib_cs_convMethod' => 'mbstring',
        't3lib_cs_utils' => 'mbstring',
    ],
    'WECHAT' => [
        'appid' => '',
        'appsecret' => '',
        'key' => '',
        'mchid' => '',
    ],
];
